### ISSUE TITLE
[BUG] ITEM.TYPE not being input

### ISSUE THREAD

**Issue by Tibladar** [Andross96/SuperLog#1]
**System info:**  
 - **OS** : Ubuntu 16.04
 - **Plugin version:** v1.1.1
 - **API Version**: Paper 1.14.4 160
-----------------------------
**Describe the bug**  
Having the following in config (taken from your website):
```
    EntityPickupItemEvent:
      enabled: true
      message: '{TYPE} picked up {ITEM.TYPE}'
```
the event always results in something like
`[EntityPickupItemEvent]: ZOMBIE picked up {ITEM.TYPE}`

**Comment by Andross96** [comment]
Hello,

It is a mistake in the documentation, the correct variable is _{ITEM.NAME}_.
I have updated the doc, and changed this.
Thanks for the report and sorry for the inconvenience.
