### ISSUE TITLE
Database feature

### ISSUE THREAD

**Issue by fmohican** [Andross96/SuperLog#2]
Hi!
I just saw your plugin, i was wondering if you could add option for mysql / mariadb.
To save logs in SQL database instead of file.

Thanks!

**Comment by Andross96** [comment]
Hello,

It is not planned, but I will maybe add this into a next version.

**Comment by fmohican** [comment]
would be a great feature, I mean if the plugin save logs in db would be
much easier to find a log via 3rd party app. (in my case php + ajax)
